apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: db-namespace
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres123"
  POSTGRES_DB: "messages_db"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres123"

